restylers:
  - name: prettier
    arguments: ['--write']
    include:
      - '**/*.css'
      - '**/*.js'
      - '**/*.json'
      - '**/*.jsx'
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.yaml'
      - '**/*.yml'

  - name: stylelint
    arguments: ['--fix']
    include:
      - '**/*.css'

  - name: eslint
    arguments: ['--fix']
    include:
      - '**/*.js'
      - '**/*.json'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
