name: DVC Download Link Check

on:
  deployment_status:

jobs:
  run:
    name: Initialize
    runs-on: ubuntu-latest
    if:
      ${{ github.event.deployment.ref != github.event.repository.default_branch
      && github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment_status.description, 'Heroku') }}
    steps:
      - uses: actions/checkout@v3
      - name: Download Link Checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args:
            --verbose "${{ github.event.deployment.payload.web_url }}" --base
            "${{ github.event.deployment.payload.web_url }}" --include
            /download/

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Check for Error Report
        if: hashFiles('./lychee/out.md') != ''
        run: |
          echo 'Errors were reported while checking the DVC download links.'
          exit 1
